# Generated by Django 5.2.1 on 2025-08-18 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('store_name', models.CharField(max_length=255, null=True, unique=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_type', models.CharField(max_length=255, unique=True)),
                ('price', models.BigIntegerField(null=True)),
                ('quantity', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=20)),
                ('user_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigIntegerField(null=True)),
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('total_products_online', models.BigIntegerField(default=0)),
                ('subscription_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
