# Generated by Django 5.2.5 on 2025-08-18 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('total_products_online', models.BigIntegerField(default=0)),
                ('subscription_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
