# Generated by Django 5.2.5 on 2025-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_type', models.CharField(max_length=255, unique=True)),
                ('price', models.BigIntegerField(null=True)),
                ('quantity', models.BigIntegerField(null=True)),
            ],
        ),
    ]
