# Generated by Django 5.2.5 on 2025-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
