# Generated by Django 5.2.5 on 2025-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
