# Generated by Django 5.2.5 on 2025-08-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
        ),
    ]
