# Generated by Django 5.2.5 on 2025-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='shop_type',
            field=models.CharField(default='NN', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_type',
            field=models.CharField(default='NN', max_length=255),
        ),
    ]
