# Generated by Django 5.2.5 on 2025-08-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.CharField(default='NN', max_length=255),
        ),
    ]
