# Generated by Django 5.2.5 on 2025-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_product_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(max_length=50000)),
                ('product_id', models.BigIntegerField(max_length=50000)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField(max_length=50000)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('store_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.BigIntegerField(default=1, null=True)),
            ],
        ),
    ]
