# Generated by Django 5.2.5 on 2025-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
