# Generated by Django 5.2.5 on 2025-08-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_cart_price_alter_cart_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('status', models.CharField(default='Processing', max_length=100)),
            ],
        ),
    ]
