# Generated by Django 5.2.5 on 2025-08-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.CharField(default='NN', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='NN', max_length=255),
        ),
    ]
